---
- name: Install apt dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - software-properties-common
      - apt-transport-https
      - curl
    state: present

- name: Add Microsoft GPG key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Visual Studio Code repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install Visual Studio Code
  become: yes
  apt:
    update_cache: yes
    name: code
    state: present
