---
- name: Install apt dependencies
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libsqlite3-dev
      - libreadline-dev
      - libffi-dev
      - curl
      - libbz2-dev
  
- name: Download Python tar
  get_url:
    url: "{{ python_from_source_url }}"
    dest: /tmp/Python-{{ python_version }}.tar.xy

- name: Ensure Python opt directory exists
  become: yes
  file:
    name: /opt/Python-{{ python_version }}
    state: directory

- name: Extract Python tar
  become: yes
  unarchive:
    remote_src: yes
    src: /tmp/Python-{{ python_version }}.tar.xy
    dest: /opt/

- name: Run Python configure script
  become: yes
  command: 
    chdir: /opt/Python-{{ python_version }}
    cmd: ./configure --enable-optimizations

- name: Get number of cores on system
  command: nproc
  register: nproc_output

- name: Start the build process
  become: yes
  make:
    chdir: /opt/Python-{{ python_version }}
    params:
      NUM_THREADS: "{{ nproc_output.stdout }}"

- name: Install Python
  become: yes
  make:
    chdir: /opt/Python-{{ python_version }}
    target: altinstall

- name: Set proper the /opt/Python-x.x.x directory to be accessible by anyone
  become: yes
  file:
    path: /opt/Python-{{ python_version }}
    mode: '0777'
    recurse: yes 