---
- name: Copy Jetbrains Toolkit installer script to the target
  copy:
    src: install-jetbrains-toolbox.sh
    dest: /tmp

- name: Make Jetbrains Toolkit installer script executable
  file:
    dest: /tmp/install-jetbrains-toolbox.sh
    mode: a+x

- name: Ensure necessary packages are installed
  apt:
    update_cache: yes
    name: curl
    state: latest

- name: Run Jetbrains Toolkit installer script
  shell: 
    cmd: /tmp/install-jetbrains-toolbox.sh
    chdir: /tmp
